### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/snserver_ynh#18] opened 2021-04-30 17:43 UTC
I tried to install it one or two months ago without success and now it did not succeed either:

https://paste.yunohost.org/raw/okiredunih

**Comment by SovereignNode** [comment] 2021-05-01 09:29
Can confirm, even with updated YunoHost version. Issue still related to Mimemagic

https://paste.yunohost.org/raw/okiredunih

**Comment by FabianWilkens** [comment] 2021-05-01 09:46
Just tested the installation.
With yunohost_version: 4.1.8 (Stable) it is working.

You are both using yunohost_version: 4.2.3.1
So i guess this is the testing version of Yunohost?

I found where the problem is.
The install script can't find a variable, because the Yunohost scripts where changed in version 4.2

.
> 
> 
> Can confirm, even with updated YunoHost version. Issue still related to Mimemagic
> 
> https://paste.yunohost.org/raw/okiredunih

It is no problem with Mimemagic

**Comment by FabianWilkens** [comment] 2021-05-01 10:27
I haven't tested this but I think you can install it with this change.

`sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/ynh_4.2`

**Comment by SovereignNode** [comment] 2021-05-01 12:49
I can see it's using 4.2.3.1 in the logs however I never installed any testing version. The Yunohost UI shows 4.1.8 (Stable)

Tried running your patch with the above command but install failed aswell

**Comment by FabianWilkens** [comment] 2021-05-01 13:09
Can you share the log?

I will take a look when I am home

**Comment by SovereignNode** [comment] 2021-05-01 13:16
https://paste.yunohost.org/raw/pabuqetehi

**Comment by FabianWilkens** [comment] 2021-05-05 16:51
@TheNomad11 @SovereignNode 
Should both be fixed now.

You can install the newest version with:
`sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh`
or wait a few hours until the app catalog to be up to date.

**Comment by TheNomad11** [comment] 2021-05-08 09:26
Installation completed, it seems , but could not test it as the VPS that I used for testing Yunohost 4.2 only has 1GB RAM and two chores which was not enough. This app seems to need a very powerful server, maybe you can add the installation requirements in the Readme?

**Comment by FabianWilkens** [comment] 2021-05-13 16:07
Thanks for the tipp.
The install and operation requierments are now in the Readme.

It should be possible for you to run the server.

I close the issue now.
Feel free to reopen or create a new one.

**Closed by FabianWilkens** 2021-05-13 16:07 UTC
